{{- if eq .Values.nacos.storage.type "mysql"}}
apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ .Values.nacos.storage.db.host }}
  namespace: {{ .Values.namespace }}
  labels:
    name: mysql

spec:
  replicas: 1
  selector:
    name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
        - name: {{ .Values.nacos.storage.db.host }}
          image: nacos/nacos-mysql:5.7
          ports:
            - containerPort: {{ .Values.nacos.storage.db.port }}
          volumeMounts:
            - name: mysql-init-script
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: {{ .Values.nacos.storage.db.name }}
            - name: MYSQL_USER
              value: {{ .Values.nacos.storage.db.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.nacos.storage.db.password }}
      volumes:
        - name: mysql-init-script
          configMap:
            name: mysql-init-script
        - name: mysql-data
{{- end }}

---
{{- if eq .Values.nacos.storage.type "mysql"}}
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
  labels:
    name: mysql
spec:
  ports:
    - port: {{ .Values.nacos.storage.db.port }}
      targetPort: {{ .Values.nacos.storage.db.port }}
  selector:
    name: mysql
{{- end }}
